name: SSH Login to Server on File Change

on:
  push:        # Trigger when files are pushed
    branches:
      - main   # Change to your branch name if different
  pull_request: # Also trigger when PRs are opened/updated

jobs:
  ssh-login:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: SSH into server
        env:
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_PASS: ${{ secrets.SERVER_PASS }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_PORT: ${{ secrets.SERVER_PORT }} # Add port as secret
        run: |
          sshpass -p "$SERVER_PASS" ssh -p "$SERVER_PORT" -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST "echo 'Logged in after file change on custom port!' && uname -a"
